### ISSUE TITLE
下载视频报错

### ISSUE THREAD

**Issue by OvO7000** [rabbitism/GadioVideo#28]
下载[魔兽故事电台卷一](https://www.gcores.com/radios/19603)时发生以下报错：
...
0 has no corresponding image, load cover as backup
Creating cover page
Traceback (most recent call last):
  File "A:\...\GadioVideo-master\gcores.py", line 36, in <module>
    main(int(title), skip_crawling, with_quote)
  File "A:\...\GadioVideo-master\gcores.py", line 15, in main
    Video.create_video(radio)
  File "A:\...\GadioVideo-master\gadio\media\video.py", line 35, in create_video
    video.write(frame)
cv2.error: Unknown C++ exception from OpenCV code

环境是windows10，Python 3.9.7
还有下载后的视频都是没有声音的，不知道是哪里的问题

**Comment by rabbitism** [comment]
关于没有音频的问题，怀疑是我写错了，现在没有网络，接下来会按照这个来修改
https://stackoverflow.com/questions/40445885/no-audio-when-adding-mp3-to-videofileclip-moviepy
